import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://www.lasvegasnevadahomesales.com'

  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '*.json',
          '/test/',
          '/dev/',
          '/wp-*/',
          '/wp-login.php',
          '*/feed/',
          '*/feed',
          '/home-2/',
          '/home-3/',
          '/contact-2/',
          '/services/investment-opportunities/feed/',
          '/las-vegas-homes/home-selling-strategies/feed/',
          '/manifest.webmanifest',
          '/opengraph-image',
          '/twitter-image',
          '/author/',
          '/2019/',
          '/438/',
          '*/replytocom=*',
          '*/utm_source=*',
          '*/utm_medium=*',
          '*/utm_campaign=*',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/test/',
          '/dev/',
          '/wp-*/',
          '/wp-login.php',
          '*/feed/',
          '*/feed',
          '/home-2/',
          '/home-3/',
          '/contact-2/',
          '/services/investment-opportunities/feed/',
          '/las-vegas-homes/home-selling-strategies/feed/',
          '/manifest.webmanifest',
          '/opengraph-image',
          '/twitter-image',
          '/author/',
          '/2019/',
          '/438/',
          '*/replytocom=*',
          '*/utm_source=*',
          '*/utm_medium=*',
          '*/utm_campaign=*',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '/test/',
          '/dev/',
          '/wp-*/',
          '/wp-login.php',
          '*/feed/',
          '*/feed',
          '/home-2/',
          '/home-3/',
          '/contact-2/',
          '/services/investment-opportunities/feed/',
          '/las-vegas-homes/home-selling-strategies/feed/',
          '/manifest.webmanifest',
          '/opengraph-image',
          '/twitter-image',
          '/author/',
          '/2019/',
          '/438/',
          '*/replytocom=*',
          '*/utm_source=*',
          '*/utm_medium=*',
          '*/utm_campaign=*',
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
} 